
FROM node:20-alpine as build-stage
WORKDIR /app
COPY src/ui/digital-twin-dashboard/package*.json ./
RUN npm install
COPY src/ui/digital-twin-dashboard/ .
RUN npm run build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
